### ISSUE TITLE
Исправление замечаний

### ISSUE THREAD

**Issue by 1that** [moevm/nosql2h24-cleaning#102]
1. http://localhost:8080/cleaning/client672e9b383565edfa236c4a64/my-addresses при добавление адреса учтите, что у домов бывают корпуса и литеры

2. http://localhost:8080/cleaning/client672e9b383565edfa236c4a64/history-order

- нужен фильтр по всем полям заказов (отдельные поисковые поля, чтобы сделать комплексный запрос по нескольким критериям)

- нужно чтобы элементы были кликабельны и переходили на страницу отдельного заказа
- При попытке найти заказы до 16.12.2023 (не вводя дату От) ошибка- 8080/api/v1/users/10/addresses:1 ￼ Failed to load resource: the server responded with a status of 500 (Internal Server Error)

3. При вводе параметров заказа нет валидации для числовых полей (а должна быть) - можно указать астрономические площади

4. Вот тут не реагирует на кнопку Добавить (Надо бы визуализировать, что что-то куда-то доабвилось)
![image](https://github.com/user-attachments/assets/4a949da3-385b-405b-9fc1-500179e40c72)
Нажатие кнопки Далее в экране набора услуг для клиента никуда не приводит (ничего не происходит)

5. При попытке авторизации под Исполнителем ничего не происходит (только форма логина очищается)
6. http://localhost:8080/cleaning/admin/workers
- отобразите все поля исполнителя на карточке + дата регистрации + количество заказов
- дополните недостающими фильтрами поиск 
- пытаюсь отредактировать исполнителя, меняю имя,  нажимаю Подтвердить

7. Редактирование услуг под админом показывает пустые формы (там нет данных редактируемой услуги
![image](https://github.com/user-attachments/assets/13d7911b-ab4c-4cab-a738-81aa15c6855f)

**Comment by Ajems** [comment]
изменить запросы getClientAddresses и createNewAddress используя axios
Убедиться что получение адресов пользователя работает корректно
